# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'caser_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(436, 341)
        self.gridLayout_14 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.tabWidget_species = QtWidgets.QTabWidget(Dialog)
        self.tabWidget_species.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget_species.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget_species.setObjectName("tabWidget")
        self.tab_location = QtWidgets.QWidget()
        self.tab_location.setObjectName("tab")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.tab_location)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.label_3_id = QtWidgets.QLabel(self.tab_location)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3_id.setFont(font)
        self.label_3_id.setObjectName("label_3")
        self.gridLayout_11.addWidget(self.label_3_id, 0, 0, 1, 1)
        self.lineEdit_3_id = QtWidgets.QLineEdit(self.tab_location)
        self.lineEdit_3_id.setMinimumSize(QtCore.QSize(311, 0))
        self.lineEdit_3_id.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_3_id.setObjectName("lineEdit_3")
        self.gridLayout_11.addWidget(self.lineEdit_3_id, 0, 1, 1, 3)
        self.label_6_code = QtWidgets.QLabel(self.tab_location)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6_code.setFont(font)
        self.label_6_code.setObjectName("label_6")
        self.gridLayout_11.addWidget(self.label_6_code, 1, 0, 1, 1)
        self.lineEdit_5_code = QtWidgets.QLineEdit(self.tab_location)
        self.lineEdit_5_code.setMinimumSize(QtCore.QSize(311, 0))
        self.lineEdit_5_code.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_5_code.setObjectName("lineEdit_5")
        self.gridLayout_11.addWidget(self.lineEdit_5_code, 1, 1, 1, 3)
        self.label_9_large_scale = QtWidgets.QLabel(self.tab_location)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_9_large_scale.setFont(font)
        self.label_9_large_scale.setObjectName("label_9")
        self.gridLayout_11.addWidget(self.label_9_large_scale, 2, 0, 1, 2)
        self.comboBox_4_large_scale = QtWidgets.QComboBox(self.tab_location)
        self.comboBox_4_large_scale.setMaximumSize(QtCore.QSize(78, 16777215))
        self.comboBox_4_large_scale.setObjectName("comboBox_4")
        self.gridLayout_11.addWidget(self.comboBox_4_large_scale, 2, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(189, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem, 2, 3, 1, 1)
        self.gridLayout_2_coords = QtWidgets.QGridLayout()
        self.gridLayout_2_coords.setObjectName("gridLayout_2")
        self.label_longitude = QtWidgets.QLabel(self.tab_location)
        self.label_longitude.setObjectName("label")
        self.gridLayout_2_coords.addWidget(self.label_longitude, 0, 0, 1, 1)
        self.lineEdit_longitude = QtWidgets.QLineEdit(self.tab_location)
        self.lineEdit_longitude.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_longitude.setObjectName("lineEdit")
        self.gridLayout_2_coords.addWidget(self.lineEdit_longitude, 0, 1, 1, 1)
        self.toolButton_3_dms = QtWidgets.QToolButton(self.tab_location)
        self.toolButton_3_dms.setMinimumSize(QtCore.QSize(0, 59))
        self.toolButton_3_dms.setObjectName("toolButton_3")
        self.gridLayout_2_coords.addWidget(self.toolButton_3_dms, 0, 2, 2, 1)
        self.label_2_latitude = QtWidgets.QLabel(self.tab_location)
        self.label_2_latitude.setObjectName("label_2")
        self.gridLayout_2_coords.addWidget(self.label_2_latitude, 1, 0, 1, 1)
        self.lineEdit_2_latitude = QtWidgets.QLineEdit(self.tab_location)
        self.lineEdit_2_latitude.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_2_latitude.setObjectName("lineEdit_2")
        self.gridLayout_2_coords.addWidget(self.lineEdit_2_latitude, 1, 1, 1, 1)
        self.gridLayout_11.addLayout(self.gridLayout_2_coords, 3, 0, 1, 4)
        spacerItem1 = QtWidgets.QSpacerItem(20, 11, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_11.addItem(spacerItem1, 4, 3, 1, 1)
        self.gridLayout_6_reference = QtWidgets.QGridLayout()
        self.gridLayout_6_reference.setObjectName("gridLayout_6")
        self.label_4_reference = QtWidgets.QLabel(self.tab_location)
        self.label_4_reference.setObjectName("label_4")
        self.gridLayout_6_reference.addWidget(self.label_4_reference, 0, 0, 1, 1)
        self.comboBox_reference = QtWidgets.QComboBox(self.tab_location)
        self.comboBox_reference.setMinimumSize(QtCore.QSize(241, 0))
        self.comboBox_reference.setObjectName("comboBox")
        self.gridLayout_6_reference.addWidget(self.comboBox_reference, 0, 1, 1, 1)
        self.gridLayout_11.addLayout(self.gridLayout_6_reference, 5, 0, 1, 4)
        self.gridLayout_3_outbreak_layer = QtWidgets.QGridLayout()
        self.gridLayout_3_outbreak_layer.setObjectName("gridLayout_3")
        self.label_10_outbreak_layer = QtWidgets.QLabel(self.tab_location)
        self.label_10_outbreak_layer.setObjectName("label_10")
        self.gridLayout_3_outbreak_layer.addWidget(self.label_10_outbreak_layer, 0, 0, 1, 1)
        self.comboBox_5_outbreak_layer = QtWidgets.QComboBox(self.tab_location)
        self.comboBox_5_outbreak_layer.setMinimumSize(QtCore.QSize(241, 0))
        self.comboBox_5_outbreak_layer.setObjectName("comboBox_5")
        self.gridLayout_3_outbreak_layer.addWidget(self.comboBox_5_outbreak_layer, 0, 1, 1, 1)
        self.gridLayout_11.addLayout(self.gridLayout_3_outbreak_layer, 6, 0, 1, 4)
        self.tabWidget_species.addTab(self.tab_location, "")
        self.tab_2_disease = QtWidgets.QWidget()
        self.tab_2_disease.setObjectName("tab_2")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.tab_2_disease)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.gridLayout_5_disease = QtWidgets.QGridLayout()
        self.gridLayout_5_disease.setObjectName("gridLayout_5")
        self.label_5_disease = QtWidgets.QLabel(self.tab_2_disease)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5_disease.setFont(font)
        self.label_5_disease.setObjectName("label_5")
        self.gridLayout_5_disease.addWidget(self.label_5_disease, 0, 0, 1, 1)
        self.comboBox_2_disease = QtWidgets.QComboBox(self.tab_2_disease)
        self.comboBox_2_disease.setMinimumSize(QtCore.QSize(280, 0))
        self.comboBox_2_disease.setObjectName("comboBox_2")
        self.gridLayout_5_disease.addWidget(self.comboBox_2_disease, 0, 1, 1, 1)
        self.gridLayout_12.addLayout(self.gridLayout_5_disease, 0, 0, 1, 2)
        self.gridLayout_4_num_animals = QtWidgets.QGridLayout()
        self.gridLayout_4_num_animals.setObjectName("gridLayout_4")
        self.label_11_num_animals = QtWidgets.QLabel(self.tab_2_disease)
        self.label_11_num_animals.setObjectName("label_11")
        self.gridLayout_4_num_animals.addWidget(self.label_11_num_animals, 0, 0, 1, 1)
        self.lineEdit_6_num_animals = QtWidgets.QLineEdit(self.tab_2_disease)
        self.lineEdit_6_num_animals.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_6_num_animals.setObjectName("lineEdit_6")
        self.gridLayout_4_num_animals.addWidget(self.lineEdit_6_num_animals, 0, 1, 1, 1)
        self.gridLayout_12.addLayout(self.gridLayout_4_num_animals, 1, 0, 1, 2)
        self.tableWidget = QtWidgets.QTableWidget(self.tab_2_disease)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.tableWidget.setFont(font)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget.setWordWrap(True)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setStretchLastSection(False)
        self.gridLayout_12.addWidget(self.tableWidget, 2, 0, 1, 1)
        self.gridLayout_10_species_add_remove = QtWidgets.QGridLayout()
        self.gridLayout_10_species_add_remove.setObjectName("gridLayout_10")
        self.toolButton_species_add = QtWidgets.QToolButton(self.tab_2_disease)
        self.toolButton_species_add.setMinimumSize(QtCore.QSize(25, 25))
        self.toolButton_species_add.setObjectName("toolButton")
        self.gridLayout_10_species_add_remove.addWidget(self.toolButton_species_add, 0, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_10_species_add_remove.addItem(spacerItem2, 1, 0, 1, 1)
        self.toolButton_5_species_dots = QtWidgets.QToolButton(self.tab_2_disease)
        self.toolButton_5_species_dots.setObjectName("toolButton_5")
        self.gridLayout_10_species_add_remove.addWidget(self.toolButton_5_species_dots, 2, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_10_species_add_remove.addItem(spacerItem3, 3, 0, 1, 1)
        self.toolButton_2_species_remove = QtWidgets.QToolButton(self.tab_2_disease)
        self.toolButton_2_species_remove.setMinimumSize(QtCore.QSize(25, 25))
        self.toolButton_2_species_remove.setObjectName("toolButton_2")
        self.gridLayout_10_species_add_remove.addWidget(self.toolButton_2_species_remove, 4, 0, 1, 1)
        self.gridLayout_12.addLayout(self.gridLayout_10_species_add_remove, 2, 1, 1, 1)
        self.tabWidget_species.addTab(self.tab_2_disease, "")
        self.tab_3_status = QtWidgets.QWidget()
        self.tab_3_status.setObjectName("tab_3")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.tab_3_status)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.gridLayout_7_year = QtWidgets.QGridLayout()
        self.gridLayout_7_year.setObjectName("gridLayout_7")
        self.label_8_year = QtWidgets.QLabel(self.tab_3_status)
        self.label_8_year.setMinimumSize(QtCore.QSize(46, 0))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_8_year.setFont(font)
        self.label_8_year.setObjectName("label_8")
        self.gridLayout_7_year.addWidget(self.label_8_year, 0, 0, 1, 1)
        self.lineEdit_4_year = QtWidgets.QLineEdit(self.tab_3_status)
        self.lineEdit_4_year.setMaximumSize(QtCore.QSize(81, 16777215))
        self.lineEdit_4_year.setInputMask("")
        self.lineEdit_4_year.setText("")
        self.lineEdit_4_year.setMaxLength(4)
        self.lineEdit_4_year.setFrame(True)
        self.lineEdit_4_year.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_4_year.setObjectName("lineEdit_4")
        self.gridLayout_7_year.addWidget(self.lineEdit_4_year, 0, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(118, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7_year.addItem(spacerItem4, 0, 2, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout_7_year, 0, 0, 1, 1)
        self.gridLayout_8_status = QtWidgets.QGridLayout()
        self.gridLayout_8_status.setObjectName("gridLayout_8")
        self.label_7_status = QtWidgets.QLabel(self.tab_3_status)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7_status.setFont(font)
        self.label_7_status.setObjectName("label_7")
        self.gridLayout_8_status.addWidget(self.label_7_status, 0, 0, 1, 1)
        self.comboBox_3_status = QtWidgets.QComboBox(self.tab_3_status)
        self.comboBox_3_status.setMinimumSize(QtCore.QSize(181, 0))
        self.comboBox_3_status.setObjectName("comboBox_3")
        self.gridLayout_8_status.addWidget(self.comboBox_3_status, 0, 1, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8_status.addItem(spacerItem5, 0, 2, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout_8_status, 1, 0, 1, 1)
        self.groupBox_dates = QtWidgets.QGroupBox(self.tab_3_status)
        font = QtGui.QFont()
        font.setItalic(False)
        self.groupBox_dates.setFont(font)
        self.groupBox_dates.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_dates)
        self.gridLayout.setObjectName("gridLayout")
        self.checkBox_dates_suspect = QtWidgets.QCheckBox(self.groupBox_dates)
        self.checkBox_dates_suspect.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkBox_dates_suspect.setObjectName("checkBox")
        self.gridLayout.addWidget(self.checkBox_dates_suspect, 0, 0, 1, 1)
        self.dateEdit_dates_suspect = QtWidgets.QDateEdit(self.groupBox_dates)
        self.dateEdit_dates_suspect.setCalendarPopup(True)
        self.dateEdit_dates_suspect.setObjectName("dateEdit")
        self.gridLayout.addWidget(self.dateEdit_dates_suspect, 0, 1, 1, 1)
        self.checkBox_2_dates_confirmation = QtWidgets.QCheckBox(self.groupBox_dates)
        self.checkBox_2_dates_confirmation.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkBox_2_dates_confirmation.setObjectName("checkBox_2")
        self.gridLayout.addWidget(self.checkBox_2_dates_confirmation, 1, 0, 1, 1)
        self.dateEdit_2_dates_confirmation = QtWidgets.QDateEdit(self.groupBox_dates)
        self.dateEdit_2_dates_confirmation.setCalendarPopup(True)
        self.dateEdit_2_dates_confirmation.setObjectName("dateEdit_2")
        self.gridLayout.addWidget(self.dateEdit_2_dates_confirmation, 1, 1, 1, 1)
        self.checkBox_3_dates_expiration = QtWidgets.QCheckBox(self.groupBox_dates)
        self.checkBox_3_dates_expiration.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkBox_3_dates_expiration.setObjectName("checkBox_3")
        self.gridLayout.addWidget(self.checkBox_3_dates_expiration, 2, 0, 1, 1)
        self.dateEdit_3_dates_expiration = QtWidgets.QDateEdit(self.groupBox_dates)
        self.dateEdit_3_dates_expiration.setCalendarPopup(True)
        self.dateEdit_3_dates_expiration.setObjectName("dateEdit_3")
        self.gridLayout.addWidget(self.dateEdit_3_dates_expiration, 2, 1, 1, 1)
        self.gridLayout_9.addWidget(self.groupBox_dates, 2, 0, 1, 1)
        self.tabWidget_species.addTab(self.tab_3_status, "")
        self.tab_4_notes = QtWidgets.QWidget()
        self.tab_4_notes.setObjectName("tab_4")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.tab_4_notes)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.textEdit_notes = QtWidgets.QTextEdit(self.tab_4_notes)
        self.textEdit_notes.setObjectName("textEdit")
        self.gridLayout_13.addWidget(self.textEdit_notes, 0, 0, 1, 1)
        self.tabWidget_species.addTab(self.tab_4_notes, "")
        self.gridLayout_14.addWidget(self.tabWidget_species, 0, 0, 1, 2)
        self.label_12 = QtWidgets.QLabel(Dialog)
        self.label_12.setText("")
        self.label_12.setObjectName("label_12")
        self.gridLayout_14.addWidget(self.label_12, 1, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Save)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout_14.addWidget(self.buttonBox, 1, 1, 1, 1)

        self.retranslateUi(Dialog)
        self.tabWidget_species.setCurrentIndex(0)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_3_id.setText(_translate("Dialog", "ID:"))
        self.label_6_code.setText(_translate("Dialog", "Code:"))
        self.label_9_large_scale.setText(_translate("Dialog", "Large scale:"))
        self.label_longitude.setText(_translate("Dialog", "Longitude:"))
        self.toolButton_3_dms.setText(_translate("Dialog", "dms"))
        self.label_2_latitude.setText(_translate("Dialog", "Latitude:"))
        self.label_4_reference.setText(_translate("Dialog", "Reference layer:"))
        self.label_10_outbreak_layer.setText(_translate("Dialog", "Outbreak layer:"))
        self.tabWidget_species.setTabText(self.tabWidget_species.indexOf(self.tab_location), _translate("Dialog", "Location"))
        self.label_5_disease.setText(_translate("Dialog", "Disease:"))
        self.label_11_num_animals.setText(_translate("Dialog", "Number of animals:"))
        self.tableWidget.setSortingEnabled(True)
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Species"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Type of production"))
        self.toolButton_species_add.setText(_translate("Dialog", "+"))
        self.toolButton_5_species_dots.setText(_translate("Dialog", "..."))
        self.toolButton_2_species_remove.setText(_translate("Dialog", "-"))
        self.tabWidget_species.setTabText(self.tabWidget_species.indexOf(self.tab_2_disease), _translate("Dialog", "Disease"))
        self.label_8_year.setText(_translate("Dialog", "Year:"))
        self.label_7_status.setText(_translate("Dialog", "Status:"))
        self.groupBox_dates.setTitle(_translate("Dialog", "Dates"))
        self.checkBox_dates_suspect.setText(_translate("Dialog", "Suspect:"))
        self.checkBox_2_dates_confirmation.setText(_translate("Dialog", "Confirmation:"))
        self.checkBox_3_dates_expiration.setText(_translate("Dialog", "Expiration:"))
        self.tabWidget_species.setTabText(self.tabWidget_species.indexOf(self.tab_3_status), _translate("Dialog", "Status"))
        self.tabWidget_species.setTabText(self.tabWidget_species.indexOf(self.tab_4_notes), _translate("Dialog", "Notes"))

